# config
admin:
  tag: develop-SNAPSHOT
zilla:
  tag: develop-SNAPSHOT

udf:
  python:
    env:
      - OPENAI_API_KEY=<your OpenAI API key>
keycloak:
  realm: zillabase
  users:
    - username: fred
      email: john.doe@example.com
      name: Fred Doe
      password: Test@123
    - username: greg
      email: jane.doe@example.com
      name: Greg Doe
      password: Test@123
  client:
    client-id: streampay
    redirects:
      - http://localhost:8084/*
      - https://oauth.pstmn.io/v1/callback
